### PR TITLE
Typo

### LINKED ISSUE #92: Simple typo in "Activity" pane
### Discord Discussion Link

_No response_

### What browsers are you seeing the problem on?

Firefox, Chrome, Brave

### What were you trying to do?

Viewing activity of my wallet

### What did not work?

Says
"All your new transaction will show up here."
Should say
"All of your new transactions will show up here."

### Version

None

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Denis2626**
resolves #92

### CODE REVIEW

File: ui/components/Wallet/WalletActivityDetails.tsx [hunk 1]
```diff
@@ -17,6 +17,19 @@ import { getBlockExplorerURL } from "../../utils/networks"
 function DetailRowItem(props: ActivityDetail): ReactElement {
   const { assetIconUrl, label, value } = props
 
+  function truncateValue(value: string) {
```
Comment (jdowning100) [inline ui/components/Wallet/WalletActivityDetails.tsx]: What typo does this fix?

Comment (Denis2626) [reply ui/components/Wallet/WalletActivityDetails.tsx]: resolves only the typo in messages.json 

the rest of the code is from a commit which is present here https://github.com/PelagusWallet/pelagus-extension/pull/94

**Comment by jdowning100** [comment]
Please remove the duplicate commit

**Review by robschleusner — APPROVED** [review]

**Review by jdowning100 — APPROVED** [review]
